# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
    # Web API Project:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "src/MoviesService.API/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "wednesday"
    open-pull-requests-limit: 5
    
    # Application project:
  - package-ecosystem: "nuget"
    directory: "src/MoviesService.Application/" 
    schedule:
      interval: "weekly"
      day: "wednesday"
    open-pull-requests-limit: 5
    
    # Infrastructure project:
  - package-ecosystem: "nuget"
    directory: "src/MoviesService.Infrastructure/" 
    schedule:
      interval: "weekly"
      day: "wednesday"
    open-pull-requests-limit: 5
    
    # Entities project:
  - package-ecosystem: "nuget"
    directory: "src/MoviesService.Domain/"
    schedule:
      interval: "weekly"
      day: "wednesday"
    open-pull-requests-limit: 5
