version: '3.3'

services:
  # Service 1: InfluxDB
  influxdb:
    restart: unless-stopped
    container_name: influxdb
    image: influxdb:1.8-alpine
    volumes:
      - ./influxdb/etc:/etc/influxdb_s6
    ports:
      - 8089:8086
    privileged: true
    environment:
      - INFLUXDB_DB=moviesservice
    networks:
      static-network:

  # Service 2: Grafana
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 4001:4000
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana_s6
    environment:
      -  ASD
      #- GF_INSTALL_PLUGINS=grafana-k6-app
    networks:
      static-network:
    depends_on:
      - influxdb

# Internal network for the containers to use
networks:
  static-network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/16

# Data volumes for containers to store information in
volumes:
  grafana_data: