// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoviesService.Infrastructure.Contexts;

#nullable disable

namespace MoviesService.API.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    [Migration("20221209115357_AzureMigration")]
    partial class AzureMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MoviesService.Domain.Entities.MovieDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1c565daf-3eaa-4b60-bc11-d0a96fce249e"),
                            Description = "A Star Wars movie",
                            Name = "Star Wars VI: Return of the Jedi"
                        },
                        new
                        {
                            Id = new Guid("208e2274-db97-4ac4-b17c-27d10abca7a8"),
                            Description = "A Dune movie",
                            Name = "Dune"
                        },
                        new
                        {
                            Id = new Guid("48aff7a7-702c-40d7-bbb0-417c0d775c08"),
                            Description = "A Harry Potter movie",
                            Name = "Harry Potter & The Deathly Hallows Part 1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
